# Generated by Django 4.2.14 on 2024-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(default='posts-img/upic.png', max_length=255, upload_to='posts-img')),
                ('password', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('tellNumber', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('location', models.TextField(max_length=500, null=True)),
                ('birthday', models.DateField(max_length=100)),
                ('about', models.TextField(default='', null=True)),
                ('education', models.CharField(default='', max_length=255, null=True)),
                ('langs', models.CharField(default='', max_length=255, null=True)),
                ('t_p', models.IntegerField(default=0, null=True)),
                ('cod_posti', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
