# Generated by Django 3.2.4 on 2024-07-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofacc', models.CharField(max_length=255)),
                ('codeacc', models.CharField(max_length=255)),
                ('power', models.IntegerField(default=30, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='categorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('tellNumber', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('location', models.TextField(max_length=500)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField(max_length=100)),
                ('codeacc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilNam', models.CharField(max_length=255)),
                ('range', models.IntegerField(default=0)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proNam', models.CharField(max_length=255)),
                ('dis', models.TextField(max_length=255)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.DateField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('category', models.ManyToManyField(blank=True, to='pixel.categorise')),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discriptions', models.TextField(max_length=3255)),
                ('par', models.CharField(default='', max_length=255, null=True)),
                ('projects', models.IntegerField(default=0, null=True)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('mess', models.TextField(max_length=5000)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('resources', models.CharField(max_length=255)),
                ('dis', models.TextField(max_length=3000)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
    ]
