# Generated by Django 3.2.4 on 2024-07-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_cards_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='datetime',
            field=models.CharField(max_length=255),
        ),
    ]
