# Generated by Django 3.2.4 on 2024-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_alter_cards_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
