# Generated by Django 3.2.4 on 2024-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0006_users_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='langs',
            field=models.CharField(default='', max_length=255),
        ),
    ]
