# Generated by Django 3.2.4 on 2024-07-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0007_users_langs'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='t_p',
            field=models.CharField(default='', max_length=255),
        ),
    ]
