# Generated by Django 3.2.4 on 2024-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0009_users_cod_posti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='p_date',
            field=models.DateField(),
        ),
    ]
