# Generated by Django 3.2.4 on 2024-07-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0010_alter_posts_p_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
