# Generated by Django 3.2.4 on 2024-07-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0012_auto_20240710_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='project-6_SbXJ7es.png', upload_to='posts-img/'),
        ),
    ]
