# Generated by Django 3.2.4 on 2024-07-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0014_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='posts-img/project-6.png', upload_to='posts-img/'),
        ),
    ]
