# Generated by Django 3.2.4 on 2024-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0015_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cview',
            field=models.IntegerField(default=0),
        ),
    ]
