# Generated by Django 3.2.4 on 2024-07-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0016_posts_cview'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('c_date', models.DateField()),
                ('subject', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.posts')),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixel.users')),
            ],
        ),
    ]
