# Generated by Django 3.2.4 on 2024-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0020_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
