# Generated by Django 3.2.4 on 2024-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0021_posts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='c_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='p_date',
            field=models.DateTimeField(),
        ),
    ]
