# Generated by Django 4.2.14 on 2024-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0022_auto_20240711_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='cod_posti',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='education',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='langs',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='t_p',
            field=models.IntegerField(default=0, max_length=255, null=True),
        ),
    ]
