# Generated by Django 4.2.14 on 2024-07-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0023_alter_users_about_alter_users_cod_posti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='t_p',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
