# Generated by Django 4.2.14 on 2024-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0024_alter_users_t_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='black_list',
            field=models.BooleanField(default=False),
        ),
    ]
