# Generated by Django 4.2.14 on 2024-07-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0025_users_black_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code_name_f',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='code_name_l',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
