# Generated by Django 4.2.14 on 2024-07-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0026_users_code_name_f_users_code_name_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='code_name_f',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='code_name_l',
            field=models.CharField(default='', max_length=255),
        ),
    ]
